export const enum CountAction {
  SET_TODOS_TYPE = 'SET_TODOS_TYPE',
  UPDATE_TODO_TYPE = 'UPDATE_TODO_TYPE',
  GET_TODO_TYPE = 'GET_TODO_TYPE',
  DELETE_TODO_TYPE = 'DELETE_TODO_TYPE',
  ADD_TODO_TYPE = 'ADD_TODO_TYPE'
} 
